server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: users
    password: users
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: databases/users/changelog.xml
  security:
    jwt:
      secret-key: 1111111111111111111111111111111111111111111111111111
      expiration: 43200000 # 12 hours
      issuer: andrei