server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/programs
    username: programs
    password: programs
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: databases/programs/changelog.xml
client:
  baseUrl: localhost:8081